### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chrisbetz**
Hi,

I'd love to have Keyword and Symbol implement Serializable, so the resulting structure is serializable.

I also included a test to check stuff, but feel free to come back to me if you need further assistance in merging.

Cheers,
Chris

### CODE REVIEW

**Comment by chrisbetz** [comment]
Sorry for that Java7 trouble. Hope you find this acceptable now :)

**Comment by bpsm** [comment]
I'm curious about why do you find that you need Symbol and Keyword to be java.io.Serializable. It would seem to me that they can already be serialized to EDN text. Why is that not sufficient in your case?

**Comment by chrisbetz** [comment]
Hi Ben,

thanks for asking. Background is, that I'm using edn-java to read config
files (in EDN, obviously) to use them in my Apache Spark application.

As Spark is a _distributed_ computing engine, it distributes stuff from one
machine to another using Java serialization. Thus, I need to serialize my
configuration.

Coming from a Clojure background, I'd like the keys to my config maps being
keywords instead of Strings. However, as the config needs to be
serializable, Keyword and Symbol (as Keyword depends on this) needs to be
serializable.

Thus, with this small change, I could use edn-java and keywords, without
this change I'd have to have either my own fork (with all the overhead) or
I needed to go with Strings for map-keys.

So, I'd really, really appreciate if you could accept the pull request and
release a new version, also, so I could get rid of my manually patched
version ;)

Thanks again!

**Comment by bpsm** [comment]
Ah, I see. Though in the case of Keyword serialization is a little more complicated since Keywords are intended to be instance controlled such that `kw1.equals(kw2) == (kw1 == kw2)`. That is, any given Keyword will exist only once.

**Comment by bpsm** [comment]
Hi Chris, 
Please have a look at https://github.com/bpsm/edn-java/pull/42.
Would that meet your needs?

**Comment by chrisbetz** [comment]
Hi,

That does look good, I'll try that on Spark on Monday and keep you posted. Thanks :)

Bye

Chris

**Comment by chrisbetz** [comment]
Hi Ben,

sorry, it took me some more days. I switched to the feature branch, tested it and everything works as a breeze.

So, looks great, thanks a lot!

I'll close this, as you track stuff in #42 .

Cheers,
Chris

**Comment by bpsm** [comment]
https://github.com/bpsm/edn-java/pull/44

**Pull request closed without merging**
